@RestApiTask_HostAddress = https://localhost:5001

POST {{RestApiTask_HostAddress}}/api/submitapirequest
Content-Type: application/json
Accept: application/json

{
  "partnerkey": "FAKEGOOGLE",
  "partnerrefno": "FG-00001",
  "partnerpassword": "RkFLRVBBU1NXT1JEMTIzNA==",
  "totalamount": 1000,
  "items": [
    {
      "partneritemref": "i-00001",
      "name": "Pen",
      "qty": 4,
      "unitprice": 200
    },
    {
      "partneritemref": "i-00002",
      "name": "Ruler",
      "qty": 2,
      "unitprice": 100
    }
  ],
  "timestamp": "2025-05-16T09:30:45.0000000Z",
  "sig": "NGQyMDFkZDkyOTUyYzk4YmEwMjI5YTlhNjJmNDU4ZTFiNGNhODg2NjdhY2VlNGJlY2JjNWFhNTA5ZWY1ODkyMw=="
}